const INITIAL_CLINICAL_ASSESSMENT = "InitialClinicalAssessment";
const PHYSICIAN_SURGICAL = "PhysicianSurgical";
const PHYSICIAN_DISCHARGE = "PhysicianDischarge";
const PHYSICIAN_3_MONTH_FOLLOWUP = "Physician3MonthFollowUp";
const PHYSICIAN_12_MONTH_FOLLOWUP = "Physician12MonthFollowup";
const PHYSICIAN_24_MONTH_FOLLOWUP = "Physician24MonthFollowup";
const PHYSICIAN_PRE_12_WKS_ADVERSE_EVENT = "PhysicianPre12WkAE";
const PHYSICIAN_GENERAL_ASSESSMENT = "PhysicianGeneralAssessment";
const ASIA_SPINAL_EXAM = "ASIASpinalExam";
const REFERRAL_INBOUND = "ReferralInbound";
const REFERRAL_OUTBOUND = "ReferralOutbound";
// TODO CONTINUE

export {
  INITIAL_CLINICAL_ASSESSMENT,
  PHYSICIAN_SURGICAL,
  PHYSICIAN_DISCHARGE,
  PHYSICIAN_PRE_12_WKS_ADVERSE_EVENT,
  PHYSICIAN_3_MONTH_FOLLOWUP,
  PHYSICIAN_12_MONTH_FOLLOWUP,
  PHYSICIAN_24_MONTH_FOLLOWUP,
  PHYSICIAN_GENERAL_ASSESSMENT,
  ASIA_SPINAL_EXAM,
  REFERRAL_INBOUND,
  REFERRAL_OUTBOUND
};
