const PATIENT_CREATED = "PATIENT_CREATED";
const PATIENT_DELETED = "PATIENT_DELETED";
const ICA_CREATED = "ICA_CREATED";
const ADMISSION_CREATED = "ADMISSION_CREATED";
const PHYSICIAN_3_MONTH_FOLLOWUP_CREATED = "PHYSICIAN_3_MONTH_FOLLOWUP_CREATED";
const PHYSICIAN_12_MONTH_FOLLOWUP_CREATED =
  "PHYSICIAN_12_MONTH_FOLLOWUP_CREATED";
const PHYSICIAN_24_MONTH_FOLLOWUP_CREATED =
  "PHYSICIAN_24_MONTH_FOLLOWUP_CREATED";
const PHYSICIAN_PRE_12_WEEK_AE_CREATED = "PHYSICIAN_PRE_12_WEEK_AE_CREATED";
const PHYSICIAN_DISCHARGE_CREATED = "PHYSICIAN_DISCHARGE_CREATED";
const PHYSICIAN_SURGICAL_CREATED = "PHYSICIAN_SURGICAL_CREATED";
const PHYSICIAN_GENERAL_CREATED = "PHYSICIAN_GENERAL_CREATED";

export {
  PATIENT_CREATED,
  PATIENT_DELETED,
  ICA_CREATED,
  ADMISSION_CREATED,
  PHYSICIAN_3_MONTH_FOLLOWUP_CREATED,
  PHYSICIAN_12_MONTH_FOLLOWUP_CREATED,
  PHYSICIAN_24_MONTH_FOLLOWUP_CREATED,
  PHYSICIAN_PRE_12_WEEK_AE_CREATED,
  PHYSICIAN_DISCHARGE_CREATED,
  PHYSICIAN_SURGICAL_CREATED,
  PHYSICIAN_GENERAL_CREATED
};
